# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0023_auto_20170514_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sengimg',
            name='img',
        ),
        migrations.AddField(
            model_name='sengimg',
            name='msg_img',
            field=models.ImageField(blank=True, upload_to=b'C:\\Users\\illusion\\Desktop\\chat\\statics\\imgs'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='msg_img',
            field=models.ImageField(blank=True, upload_to=b'C:\\Users\\illusion\\Desktop\\chat\\statics\\imgs'),
        ),
    ]
